### ISSUE TITLE
It's not working properly please help

### ISSUE THREAD

**Issue by jeffreygoldsmith** [liam-armstrong/Challenges#1]
kappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappakappa

**Comment by liam-armstrong** [comment]
kys


2016-09-28 14:42 GMT-04:00 Jeffrey Goldsmith <notifications@github.com>:
